config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root to: 'events#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :events
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  after_create :attendance_send

  belongs_to :user
  belongs_to :event
  
  def attendance_send
		AttendanceMailer.participation_email(self.user, self.event.organizer, self.event).deliver_now
	end
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :attendances
	has_many :users, through: :attendances
	belongs_to :organizer, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  after_create :welcome_send
  
  has_many :attendances
	has_many :events, through: :attendances
  has_many :organizers, foreign_key: "organizer_id", class_name: "Event"

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new]
  
  def index
    @all_events = Event.all
  end

	def show
		@event = Event.find(params[:id])
  end
  
  def new
		@event = Event.new
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  
  def show
    @user = User.find(params[:id])
    stop_other_users
    @user_events = Event.where(organizer_id: @user.id)
  end

  def destroy
	  @user = User.find(params[:id])
	  @user.destroy
    flash[:alert] = "User deleted"
    redirect_to root_path
	end

  private

	def stop_other_users
		if (current_user != @user)
			flash[:error] = "Tu ne peux pas acceder à ce profil"
			redirect_to root_path
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<!-- Jumbotron -->
<div class="jumbotron text-center">
	<h1 class="display-5">Tous les évenements autour de chez toi</h1>

	<hr class="my-4 col-8">
	<p>Eventbrite-thp recense l'ensemble des évenements de ta ville, crées-en un à ton tour !</p>
	<%= link_to "Créer un evenement", new_event_path, class:"btn btn-primary" %>
</div>

<div class="album py-5 bg-light"> 
<div class="container"> 
	<div class="row"> 
		<h4 class="font-weight-bold">Evenements populaires</h4>
	</div>
	<div class="row justify-content-between">
      <% @all_events.reverse.each do |event| %>
      <div class="card col-12 mb-3">
        <div class="card-body">
          <h5 class="card-title"><%= event.title %></h5>
          <h6 class="card-subtitle mb-2 text-muted"><%= event.location %></h6>
          <h6 class="card-subtitle mb-2 text-muted"><%= "Organisé par: #{event.organizer.email}" %></h6>
          <p class="card-text"><%= event.price %> €</p>
          <%= link_to "En savoir +",  href='#', class:"btn btn-sm btn-outline-secondary" %>
        </div>
      </div>
      <% end %>
	</div>
</div>
</div>

app/views/events/new.html.erb
<h3 class="card-title text-center m-4">Créer un evenement</h3>


<div class="container col-6">

<%= form_tag events_path do %>

	<%= label_tag 'Titre' %>
	<%= text_field_tag 'Title', @event.title, placeholder: "Titre de l'evenement", class: "form-control mb-3" %>

	<%= label_tag 'Date de début' %>
	<%= text_field_tag 'start_date', @event.start_date, placeholder: "Exemple: 2020/12/12 12:00:00", class: "form-control mb-4" %>

	<%= label_tag 'Durée' %>
	<%= text_field_tag 'duration', @event.duration, placeholder: "Durée de l'evenement (multiple de 5)", class: "form-control mb-4" %>

	<%= label_tag 'Description' %>
	<%= text_area_tag 'description', @event.description, placeholder: "Description de l'evenement (artistes, thèmes etc...)", class: "form-control mb-4" %>

	<%= label_tag 'Prix' %>
	<%= text_field_tag 'price', @event.price, placeholder: "Prix", class: "form-control mb-4" %>

	<%= label_tag 'Lieu' %>
	<%= text_field_tag 'location', @event.location, placeholder: "Addresse du lieu", class: "form-control mb-4" %>

	<br/><br/>


	<%= submit_tag "Creer un evenement", class: "btn btn-primary" %>

	<% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventbriteAppThp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>

  </head>

  <body id="page-top">

  <nav class="navbar navbar-expand-lg navbar-light bg-light" id="mainNav">
    <div class="container">
      <%= link_to "Eventbriteapp", root_path, class: "navbar-brand js-scroll-trigger text-uppercase" %>

      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>

      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav text-uppercase ml-auto">

          <li class="nav-item">
            <%= link_to "Accueil", root_path, class: "nav-link js-scroll-trigger" %>
          </li>

          <li class="nav-item">
           <%= link_to "Nouvel evenement", new_event_path, class: "nav-link js-scroll-trigger" %>
         </li>

        <% if user_signed_in? %>

        <!-- Dropdown when logged in -->
        <li class="nav-item">
        <%= link_to 'Mon profil', user_path(current_user.id), :class =>"nav-link text-dark" %>
      </li>

        <li class="nav-item">
        <%= link_to 'Se déconnecter', destroy_user_session_path, method: 'delete', :class =>"nav-link text-dark" %></a>
      </li>

      <% else %>

       <li class="nav-item">
       <%= link_to 'Se connecter / S inscrire', new_user_session_path, class: "nav-link js-scroll-trigger"%></a>
      </li>

     <% end %>

   </ul>
 </div>
</div>
</nav>

<%= yield %>

</body>
</html>

app/views/users/show.html.erb
<h3 class="card-title text-center m-4">Bienvenue sur ton profil</h3>

<body class="bg-light">

    <div class="container">
      <div class="py-5 text-center">
      </div>

      <div class="row">
      <div class="col-md-4 order-md-2 mb-4">
      <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span class="text-muted">Tes informations</span>
      </h4>
      <ul class="list-group mb-3">
        <li class="list-group-item d-flex justify-content-between lh-condensed">
          <div>
            <h6 class="my-0">Prénom</h6>
            <small class="text-muted"><%= @user.first_name %></small>
          </div>
        </li>
        <li class="list-group-item d-flex justify-content-between lh-condensed">
          <div>
            <h6 class="my-0">Nom</h6>
            <small class="text-muted"><%= @user.last_name %></small>
          </div>
        </li>
        <li class="list-group-item d-flex justify-content-between lh-condensed">
          <div>
            <h6 class="my-0">Description</h6>
            <small class="text-muted"><%= @user.description %></small>
          </div>
        </li>
        <li class="list-group-item d-flex justify-content-between lh-condensed">
        <div>
          <h6 class="my-0">Email</h6>
          <small class="text-muted"><%= @user.email %></small>
        </div>
        </li>
      </ul>
      <%= link_to "Modifier mes indentifiants", edit_user_registration_path, class:"btn btn-sm btn-outline-secondary" %>

    </div>

        <div class="col-md-8 order-md-1">
          <h4 class="mb-3">Tes evenements</h4>
          <div class="album py-5 bg-light"> 
            <div class="container"> 
              <div class="row justify-content-between">
                  <% @user_events.each do |event| %>
                  <div class="card col-12 mb-3">
                    <div class="card-body">
                      <h5 class="card-title"><%= event.title %></h5>
                      <%= link_to "En savoir +",  href='#', class:"btn btn-sm btn-outline-secondary" %>
                    </div>
                  </div>
                  <% end %>
            </div>
          </div>
        </div>
  

</body>